### PR TITLE
NSIS3 support

### PR DESCRIPTION
**Pull request by piroor**
This should update files for NSIS3.

### CODE REVIEW

**Comment by piroor** [comment]
I've verified that the built binary works on both 32bit and 64bit Windows 10. Still unclear for older Windows.

**Comment by piroor** [comment]
I successfully built the fainstall.exe without these changes:

https://github.com/clear-code/fx-meta-installer/commit/2cff008a8d638f0fa37ba58ab62bf08d25ff8aeb
https://github.com/clear-code/fx-meta-installer/commit/d994fe919d270d12df1962b11dba9309a6d33803

Should I introduce them? @kenhys

**Comment by kenhys** [comment]
> Should I introduce them? @kenhys

This is because since nsis 3.0.7, there is no need to apply the above changes.

ref https://nsis.sourceforge.io/Docs/AppendixF.html#v3.07

> [Unicode](https://nsis.sourceforge.io/Docs/Chapter4.html#aunicodetarget) now defaults to true

**Review by kenhys — APPROVED** [review]
LGTM

**Comment by kenhys** [comment]
It seems ok for Windows 11 22H2 with NSIS 3.06.1 and  3.08.

**Comment by piroor** [comment]
Thanks!

**Pull request merged**
